var foodData = [
    {
        id:6,
        name:"果酱蛋糕派",
        Ename:"Birthday Squish Cake Pie",
        img:"http://seventh77.com/view/food/img/gjdg/main.png",
        m_material:[{name:"鸡蛋",num:"五个"},{name:"低筋面粉",num:"120克"},{name:"牛奶",num:"40ml"},{name:"果酱",num:"若干"}],
        n_material:[{name:"白砂糖",num:"60克"},{name:"黄油",num:"30克"},{name:"无铝泡打粉",num:"1克"}],
        step:[{
            title:"准备食材",
            cont:[],
            tips:"所有材料最好用度量工具量好量。我用的是米缸。",
            img:"http://seventh77.com/view/food/img/gjdg/step_01.jpg"
        },{
            title:"分离蛋黄，蛋清",
            cont:["因为没有分蛋器，我用的是勺子和叉子进行分离的。"],
            tips:"鸡蛋可以在冷藏室冰一会，有利于分离。",
            img:"http://seventh77.com/view/food/img/gjdg/step_02.jpg"
        },{
            title:"打匀蛋黄",
            cont:["建议买一个打蛋器，没有的话要用叉子慢慢打了~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gjdg/step_03.jpg"
        },{
            title:"加入面粉打匀",
            cont:["依次倒入黄油和白砂糖。","接着倒入面粉，打至没有小颗粒。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gjdg/step_04.jpg"
        },{
            title:"打泡",
            cont:["把蛋清倒入无油无水的容器中打至起泡。","在之中加入白砂糖。","直至打到起泡后，倒入刚才的蛋黄液中，涂匀后放入电饭煲中开始烤。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gjdg/step_05.jpg"
        },{
            title:"涂果酱",
            cont:["待电饭煲烤好后，盛出涂上果酱即可~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gjdg/step_06.jpg"
        }]
    },{
        id:5,
        name:"番茄牛腩汤",
        Ename:"Sirloin Tomato Soup",
        img:"http://seventh77.com/view/food/img/nrt/main.png",
        m_material:[{name:"牛腩",num:"半斤"},{name:"番茄",num:"三个"},{name:"洋葱",num:"半个"}],
        n_material:[{name:"香葱",num:"若干"},{name:"姜",num:"少许"},{name:"蒜",num:"少许"},{name:"盐",num:"少许"},{name:"冰糖",num:"两粒"},{name:"干辣椒",num:"四根"},{name:"八角",num:"两个"},{name:"料酒",num:"若干"}],
        step:[{
            title:"准备食材",
            cont:["牛腩切块，番茄、洋葱切瓣，香葱、蒜、姜切末。"],
            tips:"切好的牛腩要放入冷水中浸泡30分钟去血水。",
            img:"http://seventh77.com/view/food/img/nrt/step_01.jpg"
        },{
            title:"煮番茄",
            cont:["在浸泡牛腩时，可以提前炒好番茄备用。"],
            tips:"番茄炒烂就行切勿炒成番茄酱。",
            img:"http://seventh77.com/view/food/img/nrt/step_02.jpg"
        },{
            title:"沥牛腩",
            cont:["把泡好的牛腩倒入冷水锅中，煮开后去掉浮沫，捞起沥干备用。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nrt/step_03.jpg"
        },{
            title:"炒香料",
            cont:["锅里放入一定量的油。","待油7分热后放入葱、姜、蒜末，干辣椒，八角炒香。","放入洋葱炒香。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nrt/step_04.jpg"
        },{
            title:"炒牛腩",
            cont:["接着倒入牛腩，加料酒，生抽翻炒均匀。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nrt/step_05.jpg"
        },{
            title:"炖牛腩",
            cont:["牛腩炒变色后，加入开水，小火炖30分钟左右。"],
            tips:"水要没锅牛腩多些，炖得越久越香~",
            img:"http://seventh77.com/view/food/img/nrt/step_06.jpg"
        },{
            title:"煮汤",
            cont:["倒入之前炒好的番茄。","加入冰糖，盐调味。","再炖30分钟左右。"],
            tips:"最好定一个闹钟10分钟看一次，保证水不要干，切勿这一步不要加水，不然汤就没那么浓郁了。~",
            img:"http://seventh77.com/view/food/img/nrt/step_07.jpg"
        },{
            title:"出锅",
            cont:["最后把煮好的番茄汤盛出，一份美味的番茄牛腩汤就完成了。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nrt/step_08.jpg"
        }]
    },{
        id:4,
        name:"番茄虾仁蛋包饭",
        Ename:"Tomato Shrimp Omurice",
        img:"http://seventh77.com/view/food/img/dbf/main.png",
        m_material:[{name:"虾仁",num:"六个"},{name:"鸡蛋",num:"两个"},{name:"米饭",num:"一碗"},{name:"胡萝卜",num:"半截"},{name:"豌豆",num:"若干"}],
        n_material:[{name:"香葱",num:"若干"},{name:"盐",num:"少许"},{name:"鸡精",num:"少许"},{name:"料酒",num:"少许"}],
        step:[{
            title:"准备食材",
            cont:["胡萝卜切成一小块备用，番茄切片备用，豌豆剥皮，香葱切段。"],
            tips:"米饭建议用隔夜饭。",
            img:"http://seventh77.com/view/food/img/dbf/step_01.jpg"
        },{
            title:"腌虾仁",
            cont:["虾仁加入料酒食盐拌匀。","接着腌制10分钟左右。","腌制虾仁的时候，把豌豆先煮熟。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dbf/step_02.jpg"
        },{
            title:"炒虾仁",
            cont:["虾仁切成小丁，放入锅中炒至五分熟。盛出备用。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dbf/step_03.jpg"
        },{
            title:"炒米饭",
            cont:["先放入胡萝卜炒熟。","接着放入米饭，刚超过的虾仁，煮熟的豌豆，加入一定量鸡精，食盐炒3-5分钟。","炒好米饭后乘出备用。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dbf/step_04.jpg"
        },{
            title:"煎蛋皮，制番茄酱",
            cont:["鸡蛋放入碗中打至起泡。","把打好的鸡蛋液倒入锅中煎成蛋皮。","放入炒好的米饭，用蛋皮包起出锅。","把番茄放入锅中，制成番茄酱。"],
            tips:"用叉子打蛋会很方便。",
            img:"http://seventh77.com/view/food/img/dbf/step_05.jpg"
        },{
            title:"出锅",
            cont:["把制作好的番茄酱浇在蛋包饭上，撒上葱花，美味的蛋包饭就完成了~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dbf/step_06.jpg"
        }]
    },{
        id:3,
        name:"香辣红椒碎肉藕饼",
        Ename:"Spicy Red Pepper Minced Meat Lotus Cake",
        img:"http://seventh77.com/view/food/img/opbr/main.png",
        m_material:[{name:"藕",num:"一个"},{name:"猪肉",num:"半斤"},{name:"鸡蛋",num:"三个"},{name:"面粉",num:"若干"}],
        n_material:[{name:"红椒",num:"半个"},{name:"香葱",num:"若干"},{name:"蒜瓣",num:"4瓣"},{name:"姜",num:"一小节"},{name:"花椒",num:"少许"},{name:"盐",num:"少许"},{name:"酱油",num:"少许"},{name:"鸡精",num:"少许"}],
        step:[{
            title:"准备食材",
            cont:["猪肉剁成肉末，红椒、蒜瓣、姜剁碎，香葱切成一小节一小节。","藕洗干净后，去头尾，切成一片一片的。"],
            tips:"也可以准备一些蔬菜剁碎，会更好吃。",
            img:"http://seventh77.com/view/food/img/opbr/step_01.jpg"
        },{
            title:"拌肉末",
            cont:["把准备好的材料放在大碗中，加入适量的花椒、酱油、盐、鸡精，充分拌匀。","接着腌制10分钟左右。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/opbr/step_02.jpg"
        },{
            title:"调鸡蛋面糊",
            cont:["在大碗中加入大概饭勺两勺的面粉，然后再打入三个鸡蛋。","接着调成糊状，如果发现调出来的糊太干了，可以加入适量的水。"],
            tips:"调到没有面疙瘩就算调好了。",
            img:"http://seventh77.com/view/food/img/opbr/step_03.jpg"
        },{
            title:"煎藕饼",
            cont:["在藕夹中塞入腌制好的肉馅。","把藕夹裹上鸡蛋面糊就可以放入油锅中煎炸了。"],
            tips:"一定要用小火慢慢煎，火太大容易出现面皮糊了，里面还没熟。",
            img:"http://seventh77.com/view/food/img/opbr/step_04.jpg"
        },{
            title:"煎好出锅",
            cont:["待藕饼外表煎至金黄就可以出锅了~","旁边的肉圆子是因为肉准备的多了，然后做成肉圆的。味道也非常好哦~"],
            tips:"tips:心情好的朋友，也可以制作番茄酱浇在藕饼上味道会更好哦~",
            img:"http://seventh77.com/view/food/img/opbr/step_05.jpg"
        }]
    },{
        id:2,
        name:"辣爽蓝调风情土豆泥",
        Ename:"Hot Blues Mashed Potatoes",
        img:"http://seventh77.com/view/food/img/tdn/main.png",
        m_material:[{name:"土豆",num:"两个"},{name:"猪肉",num:"二两"},{name:"卷心菜",num:"半个"},{name:"火腿肠",num:"一根"}],
        n_material:[{name:"盐",num:"少许"},{name:"贵州辣椒面",num:"少许"},{name:"香菜",num:"少许"}],
        step:[{
            title:"准备食材",
            cont:["两个土豆水煮10-15分钟，猪肉剁成肉末，卷心菜剥下来洗干净后切成一节一节的，火腿肠切段。"],
            tips:"土豆开始不用去皮，水煮完之后很容易剥皮。水煮后的土豆很烫，用冷水冷却两分钟之后再剥皮。",
            img:"http://seventh77.com/view/food/img/tdn/step_01.jpg"
        },{
            title:"做土豆泥",
            cont:["把土豆去皮后放入盆中，用刀切块。","用擀面杖或者其他钝器把土豆碾碎，碾成泥状。"],
            tips:"土豆煮的越久，越容易碾成土豆泥。",
            img:"http://seventh77.com/view/food/img/tdn/step_02.jpg"
        },{
            title:"炒配菜",
            cont:["肉末炒熟。","火腿肠煎炸至外表焦黄再出锅。","卷心菜炒熟，待快熟的时候放入少许盐。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/tdn/step_03.jpg"
        },{
            title:"煎土豆泥",
            cont:["在锅中放入土豆泥和炒熟的肉末。","用小火煎土豆泥，直至出现焦黄的锅巴。"],
            tips:"焦黄的锅巴很好吃，建议可以煎久一点。",
            img:"http://seventh77.com/view/food/img/tdn/step_04.jpg"
        },{
            title:"出锅",
            cont:["待土豆泥煎好以后，就可以出锅了~","然后放入贵州辣椒面。","最后在用香菜摆盘~漂亮的食物会更美味哦~"],
            tips:"tips:搭配一杯冰牛奶会更爽~（冰牛奶解辣哦~）",
            img:"http://seventh77.com/view/food/img/tdn/step_05.jpg"
        }]
    },{
        id:1,
        name:"酸 汤 牛 肉",
        Ename:"Sour Soup Beef",
        img:"http://seventh77.com/view/food/img/stnr/main.png",
        m_material:[{name:"牛肉",num:"150克"},{name:"红酸汤",num:"一小碗"}],
        n_material:[{name:"番茄",num:"一个"},{name:"大葱",num:"一根"},{name:"生姜",num:"一节"},{name:"蒜瓣",num:"四瓣"},{name:"香菜",num:"若干"},{name:"鸡精",num:"少量"},{name:"木姜子",num:"少量"},{name:"辣椒面",num:"若干"}],
        step:[{
            title:"准备食材",
            cont:["牛肉切片，大葱切段，生姜切片，番茄切成四瓣，大蒜拍烂，香菜去茎。"],
            tips:"用带皮牛肉口感更好~",
            img:"http://seventh77.com/view/food/img/stnr/step_01.jpg"
        },{
            title:"调汤",
            cont:["在锅中倒入一定量的冷水或者冷开水，再倒入红酸汤，充分搅拌。","之后，在放入生姜，蒜瓣，大葱，番茄，木姜子。然后开大火煮沸。","待火开了之后，放入一定量的鸡精调味。再放入牛肉开始煮。"],
            tips:"不放盐会使汤鲜美。",
            img:"http://seventh77.com/view/food/img/stnr/step_02.jpg"
        },{
            title:"蘸水",
            cont:["在煮牛肉同时可以调制蘸水。","在碗里倒入一定量的辣椒面，再放入花椒，鸡精，盐巴和香菜。","汤底煮沸之后，在放入牛肉之前，先盛一定量的汤放入蘸水里。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/stnr/step_03.jpg"
        },{
            title:"出锅。",
            cont:["放入牛肉后，煮5-10分钟后即可食用。吃完饭后可以在盛一碗美味的酸汤哦~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/stnr/step_04.jpg"
        }]
    },{
        id:7,
        name:"脆臊烤茄子",
        Ename:"Roast Eggplant of Dried Meat",
        img:"http://seventh77.com/view/food/img/kqz/main.png",
        m_material:[{name:"茄子",num:"一个"},{name:"脆臊",num:"一小碗"},{name:"粉丝",num:"一小把"}],
        n_material:[{name:"蒜头",num:"一个"},{name:"香葱",num:"若干"},{name:"豆瓣酱",num:"一小勺"},{name:"花椒",num:"少许"},{name:"鸡精",num:"少许"}],
        step:[{
            title:"准备食材",
            cont:["蒜瓣剁碎，香葱切成一小节一小节。","粉丝先用水泡软后，然后过一到开水备用。"],
            tips:"粉丝过水后也要用冷水泡着，不然会凝成一团。",
            img:"http://seventh77.com/view/food/img/kqz/step_01.jpg"
        },{
            title:"烤茄子",
            cont:["烤箱200度预热10分钟。","茄子去头并切成两半，然后把茄子肉划成网格，刷油后放入烤箱。","上下火200度，中下层，烤15分钟左右。"],
            tips:"一定记住要刷油，不然会烤糊。如果想吃软一点的可以烤久一点。",
            img:"http://seventh77.com/view/food/img/kqz/step_02.jpg"
        },{
            title:"炒酱料",
            cont:["先放入蒜泥炒香，接着放入豆瓣酱爆炒。","然后倒入脆臊，小火炒一会儿。","再放入花椒，鸡精等调料，倒入一小半碗水。"],
            tips:"放水是为了让酱汁更能渗透茄子里面，这样茄子会更香。",
            img:"http://seventh77.com/view/food/img/kqz/step_03.jpg"
        },{
            title:"再烤",
            cont:["待茄子烤好后，铺上粉丝和酱汁。","上下火200度再烤10分钟。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/kqz/step_04.jpg"
        },{
            title:"出锅",
            cont:["烤好后，撒上葱花，一道美味的烤茄子就完成了~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/kqz/step_05.jpg"
        }]
    },{
        id:8,
        name:"宫保鸡丁",
        Ename:"Kung Pao Chicken",
        img:"http://seventh77.com/view/food/img/gbjd/main.png",
        m_material:[{name:"鸡胸肉",num:"300克"},{name:"油炸花生",num:"70克"},{name:"红酸汤",num:"少量"}],
        n_material:[{name:"大葱",num:"若干"},{name:"姜",num:"少许"},{name:"蒜",num:"少许"},{name:"盐",num:"少许"},{name:"白砂糖",num:"少许"},{name:"干辣椒",num:"适量"},{name:"醋",num:"少量"},{name:"料酒",num:"少量"},{name:"生抽",num:"适量"},{name:"淀粉",num:"适量"}],
        step:[{
            title:"准备食材",
            cont:["事先炸好花生。","鸡胸肉切丁，大葱、干辣椒切段，蒜、姜切末。"],
            tips:"炸花生一定要注意火候，不然容易糊。",
            img:"http://seventh77.com/view/food/img/gbjd/step_01.jpg"
        },{
            title:"腌制鸡胸肉",
            cont:["在鸡胸肉中加入少量淀粉，生抽和料酒腌制10分钟。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gbjd/step_02.jpg"
        },{
            title:"调芡汁",
            cont:["将少量生抽，白糖，醋，蒜末，姜末，淀粉，盐放入小碗中，然后加入大概两勺水调成芡汁。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gbjd/step_03.jpg"
        },{
            title:"炒鸡胸肉",
            cont:["在锅中倒入鸡胸肉，迅速滑散。","断生立马出锅。"],
            tips:"鸡胸肉不能炒太久，不然老了就不好吃了。",
            img:"http://seventh77.com/view/food/img/gbjd/step_04.jpg"
        },{
            title:"炒香料",
            cont:["在锅中放入葱姜蒜，干辣椒，小火炒出香味后再煸一会儿。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gbjd/step_05.jpg"
        },{
            title:"调味",
            cont:["接着放入鸡胸肉和油炸花生。","倒入芡汁和红酸汤不停翻炒。"],
            tips:"红酸汤可以让这道菜更美味。",
            img:"http://seventh77.com/view/food/img/gbjd/step_06.jpg"
        },{
            title:"出锅",
            cont:["大火收汁就可以出锅了。"],
            tips:"可以适量加一点香菜点翠一下~",
            img:"http://seventh77.com/view/food/img/gbjd/step_07.jpg"
        }]
    },{
        id:10,
        name:"面非面-鲶鱼面",
        Ename:"Catfish Noodles",
        img:"http://seventh77.com/view/food/img/nym/main.png",
        m_material:[{name:"鲶鱼",num:"一只(2斤左右)"},{name:"鲫鱼",num:"一只"},{name:"鱿鱼干",num:"若干"}],
        n_material:[{name:"鱼露",num:"适量"},{name:"耗油",num:"适量"},{name:"姜",num:"适量"},{name:"葱，香菜",num:"适量"},{name:"柠檬",num:"一个"},{name:"薄荷",num:"适量"},{name:"蛋清",num:"两个"},{name:"淀粉",num:"适量"}],
        step:[{
            title:"准备材料",
            cont:["鲶鱼剔骨打成泥，姜切片，切葱花，鲫鱼切块。","鱼露与耗油1:1调制备用。"],
            tips:"去越南学到一招，用香茅熬的汤会有一股淡淡的清香，十分美味。也可以用柠檬和薄荷替代香茅。",
            img:"http://seventh77.com/view/food/img/nym/step_01.jpg"
        },{
            title:"熬汤",
            cont:["把鲫鱼块，姜，葱白，薄荷放入水中开始熬制。","用力挤柠檬，滴入柠檬汁。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nym/step_02.jpg"
        },{
            title:"乘熬汤的时间处理鲶鱼泥",
            cont:["鲶鱼泥加入蛋清，淀粉，料酒揉匀。"],
            tips:"如果发现泥太松可适当加入一些面粉。",
            img:"http://seventh77.com/view/food/img/nym/step_03.jpg"
        },{
            title:"制作鲶鱼面",
            cont:["把处理好的鲶鱼泥放入裱花袋中。","在裱花袋口剪一个刚好可以放入鱿鱼丝的口子。"],
            tips:"挤出来的面条一定要放入开水中，不然很容易断掉。",
            img:"http://seventh77.com/view/food/img/nym/step_04.jpg"
        },{
            title:"煮面",
            cont:["把面条倒入锅中，煮3-5分钟。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nym/step_05.jpg"
        },{
            title:"调汤",
            cont:["汤熬得差不多后，用勺子去掉表面的一些杂质。","加入刚用鱼露和耗油调好的酱汁，再熬2-3分钟。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nym/step_06.jpg"
        },{
            title:"出锅",
            cont:["面煮好后，捞出，倒入熬好的汤。","再撒上葱花，放上香菜，一碗美味的鲶鱼面就完成了~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/nym/step_07.jpg"
        }]
    },{
        id:9,
        name:"辣子鸡",
        Ename:"Spicy Chicken",
        img:"http://seventh77.com/view/food/img/lzj/main.png",
        m_material:[{name:"鸡肉",num:"半只"},{name:"魔芋豆腐",num:"半块"}],
        n_material:[{name:"干辣椒",num:"适量"},{name:"花椒",num:"一小把"},{name:"姜",num:"半节"},{name:"蒜瓣",num:"六瓣"},{name:"八角",num:"适量"},{name:"料酒",num:"适量"},{name:"酱油",num:"适量"},{name:"盐",num:"适量"}],
        step:[{
            title:"腌制鸡肉",
            cont:["鸡肉切块后，加入适量料酒，盐巴和姜片腌制20分钟。","鸡胸肉切丁，大葱、干辣椒切段，蒜、姜切末。"],
            tips:"鸡肉炸后会变得很小块，所以可以适当切大块一点。",
            img:"http://seventh77.com/view/food/img/lzj/step_01.jpg"
        },{
            title:"准备材料",
            cont:["干辣椒切段后，滤掉辣椒籽。","魔芋豆腐切成条状。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/lzj/step_02.jpg"
        },{
            title:"炒鸡肉",
            cont:["把油倒入锅中烧热。","烧热后，把鸡肉一次性倒入锅中，开中小火翻炒。","炒至表面金黄，乘出备用。"],
            tips:"不知道油什么时候热，可以先放入一块鸡，如果炸得滋滋响就证明热了。",
            img:"http://seventh77.com/view/food/img/lzj/step_03.jpg"
        },{
            title:"炒香料",
            cont:["依次放入花椒和姜片、蒜瓣和八角、干辣椒炒香。","这时你会闻到一股非常浓烈的香味。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/lzj/step_04.jpg"
        },{
            title:"炒鸡肉",
            cont:["接着放入刚炒好的鸡肉，大火翻炒。","加入酱油调色。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/lzj/step_05.jpg"
        },{
            title:"出锅",
            cont:["最后加入魔芋豆腐，继续大货翻炒。","炒至魔芋和鸡肉表面都附上了美味调料后出锅。"],
            tips:"魔芋豆腐增加了不少美味。",
            img:"http://seventh77.com/view/food/img/lzj/step_06.jpg"
        }]
    },{
        id:11,
        name:"香糯菇蒸肉",
        Ename:"Glutinous Meat & Mushroom",
        img:"http://seventh77.com/view/food/img/gzr/main.png",
        m_material:[{name:"香菇",num:"7个"},{name:"猪肉",num:"四两"},{name:"鸡蛋",num:"一个"},{name:"胡萝卜",num:"半节"}],
        n_material:[{name:"盐",num:"少许"},{name:"葱",num:"少许"},{name:"小米椒",num:"少许"},{name:"淀粉",num:"适量"}],
        step:[{
            title:"准备食材",
            cont:["香菇洗净去跟，肉剁成肉末。","胡萝卜切成一小块一小块，葱，小米椒切好备用。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gzr/step_01.jpg"
        },{
            title:"拌肉",
            cont:["把肉放入一个大盆中，加入胡萝卜，淀粉，小米椒，适量的盐拌匀。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gzr/step_02.jpg"
        },{
            title:"摆盘",
            cont:["先在盘子里面铺上香菇。","把刚拌好的肉揉成一个一个的肉圆。","把肉圆裹上糯米放在香菇上。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gzr/step_03.jpg"
        },{
            title:"蒸香菇肉圆",
            cont:["把摆好的香菇肉圆放入蒸锅中，开大火蒸。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gzr/step_04.jpg"
        },{
            title:"出锅",
            cont:["蒸15-20分钟以后一盘美味的香糯菇蒸肉就出锅了~"],
            tips:0,
            img:"http://seventh77.com/view/food/img/gzr/step_05.jpg"
        }]
    },{
        id:12,
        name:"XO酱牛肉土豆饼",
        Ename:"XO Beef Potato Cake",
        img:"http://seventh77.com/view/food/img/tdb/main.png",
        m_material:[{name:"土豆",num:"一个"},{name:"牛肉",num:"200克"},{name:"鸡蛋",num:"两个"}],
        n_material:[{name:"洋葱",num:"1/4个"},{name:"面粉",num:"适量"},{name:"红椒",num:"两根"},{name:"青椒",num:"半根"},{name:"盐",num:"少许"},{name:"酱油",num:"适量"},{name:"蒜瓣",num:"两瓣"},{name:"黄油",num:"适量"}],
        step:[{
            title:"准备食材",
            cont:["土豆切条，洋葱切末，红椒、青椒、蒜瓣剁碎。","牛肉剁成肉末。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/tdb/step_01.jpg"
        },{
            title:"拌面",
            cont:["在大碗中加入面粉和鸡蛋拌匀。"],
            tips:"如果太干可以适量加一些水。",
            img:"http://seventh77.com/view/food/img/tdb/step_02.jpg"
        },{
            title:"加入调料",
            cont:["加入牛肉沫，碎椒，洋葱拌匀。","加入适量的盐。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/tdb/step_03.jpg"
        },{
            title:"煎土豆饼",
            cont:["把土豆饼裹上牛肉面糊，放入锅中，中小火煎炸。"],
            tips:"土豆放入锅中后，可以倒入少量牛肉面糊在上面。",
            img:"http://seventh77.com/view/food/img/tdb/step_04.jpg"
        },{
            title:"出锅",
            cont:["待土豆饼煎得金黄就可以出锅了。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/tdb/step_05.jpg"
        },{
            title:"炒酱",
            cont:["在锅放入黄油。","待黄油融掉后，放入蒜末炒香。","最后加入少许酱油，再用芡汁勾芡。"],
            tips:"炒酱时间不能太长。",
            img:"http://seventh77.com/view/food/img/tdb/step_06.jpg"
        },{
            title:"摆盘",
            cont:["最后把炒好的酱淋在土豆饼上。","用鲜橙，洋葱，薄荷等摆盘，一盘美味的土豆饼就完成了。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/tdb/step_07.jpg"
        }]
    },{
        id:13,
        name:"豆花烤鱼",
        Ename:"Grilled Fish & Tofu Pudding",
        img:"http://seventh77.com/view/food/img/dhky/main.png",
        m_material:[{name:"黑鱼",num:"1斤半"},{name:"豆花",num:"一碗"},{name:"土豆",num:"一个"},{name:"黄瓜",num:"半节"}],
        n_material:[{name:"豆瓣酱",num:"一大勺"},{name:"大葱",num:"若干"},{name:"姜",num:"少许"},{name:"蒜",num:"少许"},{name:"盐",num:"少许"},{name:"干辣椒",num:"适量"},{name:"料酒",num:"少量"},{name:"青椒",num:"2根"},{name:"花椒",num:"适量"},{name:"洋葱",num:"半个"},{name:"冰糖",num:"2颗"},{name:"香菜",num:"若干"}],
        step:[{
            title:"腌制鱼肉",
            cont:["鱼肉洗净","鱼露与耗油1:1调制备用。","把鱼肉刨开成两瓣，加入料酒、盐和胡椒腌制。","腌制一个小时左右。"],
            tips:"我选的是黑鱼，家乡那边用的是江团（鮰鱼）比较多，草鱼和鲢鱼也是不错的。",
            img:"http://seventh77.com/view/food/img/dhky/step_01.jpg"
        },{
            title:"烤鱼",
            cont:["腌制完成后，给铁板和鱼刷上油。","烤箱上下150度，中层烤25分钟左右。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dhky/step_02.jpg"
        },{
            title:"备菜",
            cont:["趁着烤鱼的这段时间可以备菜。","土豆和黄瓜削皮切条，姜和洋葱切片，青椒大葱切段，大蒜拍好，香菜干辣椒洗净备用。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dhky/step_03.jpg"
        },{
            title:"炒香料",
            cont:["热锅冷油，放入大葱、蒜瓣、姜片、花椒和干辣椒大火炒香。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dhky/step_04.jpg"
        },{
            title:"炒酱料",
            cont:["接着加入豆瓣酱和青椒炒香。","然后倒入一碗水，并把土豆和黄瓜倒入，再加入冰糖和适量的盐煮5分钟。"],
            tips:0,
            img:"http://seventh77.com/view/food/img/dhky/step_05.jpg"
        },{
            title:"再次烤鱼",
            cont:["鱼烤完后把煮好的酱料倒在鱼上，并加上豆花再次烤。","上火150度，下火250度，下层烤十分钟。"],
            tips:"考好的鱼记得翻一下，鱼肉朝上，这样才入味。",
            img:"http://seventh77.com/view/food/img/dhky/step_06.jpg"
        },{
            title:"出锅",
            cont:["烤好后，加上香菜装盘，一盘美味的豆花烤鱼就完成了。"],
            tips:"有条件的，可以继续放在烤炉上小火烤，边烤边吃，还可以加入一些小菜",
            img:"http://seventh77.com/view/food/img/dhky/step_07.jpg"
        }]
    }
]

module.exports = {
   foodData:foodData
}